### ISSUE TITLE
How to send requests with the Api key getting 'Authentication credentials were not provided' message.

### ISSUE THREAD

**Issue by abhijeet-cn** [florimondmanca/djangorestframework-api-key#134] opened 2020-06-05 11:39 UTC
Hi, I am a little lost in the working of the library. 

So what I basically did was installing the package and configuring it, then from the shell I created the API key, 
```
>>> from rest_framework_api_key.models import APIKey
>>> api_key, key = APIKey.objects.create_key(name="my-remote-service")
>>> key
```
Now I added the permission HasAPIKey to a view, but every time I am trying to access it I am getting the same message. 

`requests.get('http://localhost:8000/create/',headers={'HTTP_AUTHORIZATION':'Api-Key:m9HrGOxJ.I5cbLGwwTM1gT3xsBk8j97EtkWGzvUo5'})`

Output - 

`{'detail': 'Authentication credentials were not provided.'}`

Any help on this is appreciated, thanks!

**Comment by florimondmanca** [comment] 2020-06-05 16:25
Heya,

I think the issue is in the name of the authorization header you’re sending - it should be `Authorization` (`HTTP_AUTHORIZATION` is for Django but you’re using Requests here).

**Comment by florimondmanca** [comment] 2020-06-06 08:25
By the way you can find an example of a formatted `Authorization` in the docs: [Authorization header](https://florimondmanca.github.io/djangorestframework-api-key/guide/#authorization-header)

Going to close this for now since I think this should resolve your problem :-) If that's not the case feel free to reach back!

**Closed by florimondmanca** 2020-06-06 08:25 UTC
Labels: question

**Comment by dhiraka** [comment] 2022-01-21 06:40
I am facing this exact issue. I am trying to use apikeys along with jwt tokens
