### ISSUE TITLE
PostgreSQL: migration 0004_prefix_hashed_key never ends

### ISSUE THREAD

**Issue by kamartem** [florimondmanca/djangorestframework-api-key#113] opened 2020-04-04 13:55 UTC
**Describe the bug**
After clear install of app, migration process never ends at 0004 step. If RunPython code removed (screenshot), migration applies successful.

**Screenshots**
![Screenshot 2020-04-04 at 16 47 49](https://user-images.githubusercontent.com/48558418/78452495-29fe7200-7694-11ea-944b-418b39e5cb76.png)

**Desktop**
 - OS / Python: docker container 3.7.7-stretch based image
 - Django==3.0.5
 - djangorestframework==3.11.0
 - postgres:11.4-alpine (also tried postgres:12.2-alpine) - containerized

**Additional context**
Possible ref: [https://docs.djangoproject.com/en/3.0/ref/migration-operations/#runpython](https://docs.djangoproject.com/en/3.0/ref/migration-operations/#runpython)
On databases that do support DDL transactions (SQLite and PostgreSQL), RunPython operations do not have any transactions automatically added besides the transactions created for each migration. Thus, on PostgreSQL, for example, you should avoid combining schema changes and RunPython operations in the same migration or you may hit errors like OperationalError: cannot ALTER TABLE "mytable" because it has pending trigger events.

**Comment by florimondmanca** [comment] 2020-04-04 14:14
Hi!

- By clear install, do you mean running migrations on a blank database as well?
- Do you see any error (like the one in the docs you linked to) or does the migration simply stall?

**Comment by kamartem** [comment] 2020-04-04 14:29
Hello again.

1) Yes, tried blank db as well.
2) No error, migration process just freezes (screenshot)

![Screenshot 2020-04-04 at 17 29 03](https://user-images.githubusercontent.com/48558418/78453353-caa36080-7699-11ea-9b55-0dbedb2683e2.png)

**Comment by florimondmanca** [comment] 2020-04-04 14:43
Hmm, okay, can you turn on database debug logging and share the new output? It would be nice to see what’s causing the stall exactly. https://docs.djangoproject.com/fr/2.2/topics/logging/#django-db-backends

**Comment by kamartem** [comment] 2020-04-04 14:44
if i wait some time:

```
  Applying rest_framework_api_key.0004_prefix_hashed_key...Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 233, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/usr/local/lib/python3.7/site-packages/rest_framework_api_key/migrations/0004_prefix_hashed_key.py", line 17, in populate_prefix_hashed_key
    for api_key in model.objects.all():
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 276, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

**Comment by kamartem** [comment] 2020-04-04 14:49
![Screenshot 2020-04-04 at 17 48 55](https://user-images.githubusercontent.com/48558418/78453769-90878e00-769c-11ea-881a-5a80366912fe.png)

**Comment by florimondmanca** [comment] 2020-04-04 17:32
Thanks. I just tried running the test suite against a local Postgres database, I'm not able to reproduce the stall (Python 3.8.2, Django 3.0, DRF 3.10, Postgres 10). Will try on `postgres:12-alpine`…

(Makes me think we really should be running the test suite against at least SQLite + Postgres, instead of in-memory SQLite only…)

**Comment by florimondmanca** [comment] 2020-04-04 17:38
Ran migrations against a Postgres container too, no luck reproducing this:

```console
$ docker run -d --rm -it --name postgres12 -e POSTGRES_HOST_AUTH_METHOD=trust -p 5433:5432 postgres:12-alpine
$ docker exec -it postgres12 psql --user postgres -c 'create database "djangorestframework-api-key";'
$ test_project/manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, heroes, rest_framework_api_key, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying heroes.0001_initial... OK
  Applying heroes.0002_prefix_hashed_key... OK
  Applying rest_framework_api_key.0001_initial... OK
  Applying rest_framework_api_key.0002_auto_20190529_2243... OK
  Applying rest_framework_api_key.0003_auto_20190623_1952... OK
  Applying rest_framework_api_key.0004_prefix_hashed_key... OK
  Applying sessions.0001_initial... OK
```

**Comment by florimondmanca** [comment] 2020-04-04 17:44
Could this be an issue with the Postgres driver? I'm trying using `psycopg2-binary==2.8.4`, which version are you using?

**Comment by kamartem** [comment] 2020-04-04 17:45
psycopg2==2.8.4

**Comment by florimondmanca** [comment] 2020-04-04 17:47
Can you try using `psycopg2-binary`? At this point I'm clueless about the origin of this, we should try all possibilities… I might also test on a Python `alpine` container too to see if we have OS compatibility issues there. I've never seen a migration stall though…

**Comment by kamartem** [comment] 2020-04-04 19:16
Founded possible problem, not related to djangorestframework-api-key package. Tomorrow i will investigate and report results. Thank you for feedback

**Comment by kamartem** [comment] 2020-04-04 21:02
Problem was in custom DATABASE_ROUTERS

I have two 'databases' in conf: one for migrations ('migrate_conf'), second for 'normal' work ('normal_conf'). The only difference is username/password.

Simplifying logic:

```
class DatabaseRouter:
    def db_for_write(self, model, **hints):
        return 'normal_conf'

    def allow_migrate(self, db, app_label, model_name=None, **hints):
        if db == 'migrate_conf':
            return True
        return False
```

Then i run migrations: python manage.py migrate --database migrate_conf

I suppose datamigration (Runpython) operates on db_for_write so that is problem in my case.

Thank you again for feedback.

**Comment by florimondmanca** [comment] 2020-04-04 21:37
Ok, glad you found the issue. I’ll close this off then. :)

**Closed by florimondmanca** 2020-04-04 21:37 UTC
Labels: question
