### ISSUE TITLE
Seeking clarity on how to effectively using API keys

### ISSUE THREAD

**Issue by thatsankur** [florimondmanca/djangorestframework-api-key#94] opened 2020-01-17 02:52 UTC
Hi !

I have a model structure like 

User

- Project 1 
   -Res 1 
   -Res 2
- Project 2
   -Res 1 
   -Res 2

Now the Top and all layer is projected by JWT auth  for particular user 

Now I want to user API key at Project level and below to configure it's resources via API key 

So I created custom API key model like 

```
class ProjectAPIKeyManager(BaseAPIKeyManager):
    def get_usable_keys(self):
        return super().get_usable_keys().filter(project__active=True)
```

```
class ProjectAPIKey(AbstractAPIKey):
    objects = ProjectAPIKeyManager()
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name="api_keys",
    )

    class Meta(AbstractAPIKey.Meta):
        verbose_name = "Project API key"
        verbose_name_plural = "Project API keys"
```
 
Now I am not sure how to get Project from API key and then perform subsequent operations via that 
Please help with the documentation or example project which can let me do that.

thanks in advance it looks a good framework I am just not sure how to use it for my requirements .

**Comment by florimondmanca** [comment] 2020-01-28 19:04
Hi @thatsankur! Just came across this thread.

> how to get Project from API key

Once you've got the `ProjectAPIKey` object, you should be able to use the foreign key, i.e.…

```python
project = project_api_key.project
```

Now your question might rather be "*how I you get the `project_api_key` in the first place?*". I think this ties in with #92 and #93, which allow retrieving an API key object from the API key string. Would you mind taking a look and see if it would solve your use case?

**Comment by florimondmanca** [comment] 2020-01-28 20:40
I'm going to close this as a duplicate of #92 for now. If that's not exactly accurate feel free to reach out again. :-) Thanks!

**Closed by florimondmanca** 2020-01-28 20:40 UTC
Labels: question
